# Especificaciones
name: 'propelling_tech_challenge'
version: '1.0.0'
config-version: 2

# Perfil DBT de uso:
profile: 'default'

# Configuración estandard de carpetas:
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# Modelos:
models:
  propelling_tech_challenge:
    # Configuración por defecto para todo el proyecto (vistas)
    +materialized: view
    
    # Configuraciones específicas por carpeta (respetando tus nombres)
    01_Bronze:
      +materialized: view
    02_Silver:
      +materialized: view
    03_Gold:
      +materialized: table
